api_version = "2025-01"

[[extensions]]
type = "ui_extension"
name = "Bundlify Checkout Upsell"
handle = "bundlify-checkout"

  [[extensions.targeting]]
  module = "./src/Checkout.tsx"
  target = "purchase.checkout.cart-line-list.render-after"
